Update testsPython.yml
Added force failure for testing and If to always run notification check.

diff --git a/.github/workflows/testsPython.yml b/.github/workflows/testsPython.yml
--- a/.github/workflows/testsPython.yml
+++ b/.github/workflows/testsPython.yml
@@ -62,6 +62,10 @@ jobs:
           mysql-charset: "${{ secrets.MYSQL_CHARSET }}"
           codecov-token: "${{ secrets.CODECOV_TOKEN }}"
 
+  # Force failure for testing notifications
+      - name: Force failure
+        run: exit 1
+
   # Job #2: Notifications (Mini-capstone assignment)
   # This job will run after the Python unit tests and
   # is scaffolded to facilitate sending notifications based
@@ -69,6 +73,7 @@ jobs:
   notifications:
     needs: python-unit-tests
     runs-on: ubuntu-latest
+    if: always()
     steps:
       - name: Notify on test results
         run: |
